# This file was generated by GoReleaser. DO NOT EDIT.
cask "layergrid" do
  version "0.1.0-rc.1"

  on_macos do
    on_intel do
      sha256 "2e13dd3e708c14188be99e5fac72c3d3c4dfc9a781a48e9a36eefaa9296b075a"
      url "https://github.com/layergrid/layergrid-cli/releases/download/v#{version}/layergrid_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9eee1e0bcb7f70d600bf587fb8d724f0e7b851056f0ccd606dfe527a857d4ee3"
      url "https://github.com/layergrid/layergrid-cli/releases/download/v#{version}/layergrid_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f4de4731520476dc6f98a4a269f73cbd4a6289d66e6bd3b43c0ca736e893b6d0"
      url "https://github.com/layergrid/layergrid-cli/releases/download/v#{version}/layergrid_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "75b2fc5855ef13b204b3ec9ae771aa925a504b013580fda62df569efcc53b5ee"
      url "https://github.com/layergrid/layergrid-cli/releases/download/v#{version}/layergrid_#{version}_linux_arm64.tar.gz"
    end
  end

  name "layergrid"
  desc "Offline static scanner for AI agent stack trifecta risks"
  homepage "https://github.com/layergrid/layergrid-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "layergrid"

  # No zap stanza required

end
