# This file was generated by layergrid/layergrid-cli. DO NOT EDIT.
class Layergrid < Formula
  desc "Offline static scanner for AI agent stack trifecta risks"
  homepage "https://github.com/layergrid/layergrid-cli"
  version "0.1.0-alpha.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/layergrid/layergrid-cli/releases/download/v0.1.0-alpha.0/layergrid_0.1.0-alpha.0_darwin_amd64.tar.gz"
      sha256 "9145fd3c3115d6899c96b4ca518711b362f634f1223333540bd1b92998b8b998"
    end
    on_arm do
      url "https://github.com/layergrid/layergrid-cli/releases/download/v0.1.0-alpha.0/layergrid_0.1.0-alpha.0_darwin_arm64.tar.gz"
      sha256 "4a8f824f0de44adfe1066b9155a4b73c70e0608069e3586956bdc7f10e1b7c21"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/layergrid/layergrid-cli/releases/download/v0.1.0-alpha.0/layergrid_0.1.0-alpha.0_linux_amd64.tar.gz"
      sha256 "0be1b5b634c887a3daa468a886d7901b8eea0ea3ece76e5deebb2b0ce8b1eaaa"
    end
    on_arm do
      url "https://github.com/layergrid/layergrid-cli/releases/download/v0.1.0-alpha.0/layergrid_0.1.0-alpha.0_linux_arm64.tar.gz"
      sha256 "ec399aeae0e9f30cbe22b02259812b5435d2133b4c8aa831f88e4cf08e796b2a"
    end
  end

  def install
    bin.install "layergrid"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/layergrid version")
  end
end
